### PR TITLE
- Add virtio-console support.

### PR DESCRIPTION
**Pull request by araujobsd**
It can be used with https://github.com/araujobsd/bhyve-vm-goagent

### CODE REVIEW

**Comment by churchers** [comment]
I've been looking at a way of adding this functionality while not tying it specifically to freenas port names, and allowing up to the available 16 ports.

I must be missing something though as I just can't get virtio-console ports to show up in the guest. I'm running 11.2-RC3, which seems to have the virtio-console bhyve support that 11.1 didn't. Running the guest shows the following - 

    virt_console0="org.freenas.bhyve-agent"
      ->
    -s 2:0,virtio-console,org.freenas.bhyve-agent=/vm/bsd1/vtcon.org.freenas.bhyve-agent

Not 100% sold on the host path/filename yet but this makes it easy to specify the `freenas.bhyve-agent` port if desired, whilst still allowing the user full control over port names, or whether there's any ports at all.

However, even with the guest running 11.2, I don't get any `/dev/ttyV` or `/dev/vtcon` entries... I do get the device though so I'm not sure whether I've missed a step somewhere or need to be running 12?

    virtio_pci0: <VirtIO PCI Console adapter> port 0x2000-0x203f mem 0xc0000000-0xc0001fff irq 16 at device 2.0 on pci0

```
virtio_pci0@pci0:0:2:0: class=0x070000 card=0x00031af4 chip=0x10031af4 rev=0x00 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'Virtio console'
    class      = simple comms
    subclass   = UART
```

**Comment by araujobsd** [comment]
@churchers In the guest side you need to load the virtio_console module:`kldload virtio_console` then it will create a port `/dev/ttyV0.0` in case you have defined only one virtio-console port when you launch the VM at host side. For Linux it will open a different port name, the easiest way is you use `https://github.com/freenas/bhyve-vm-goagent/releases`, note that it is just a small binary, you don't need to build anything.

Beset,

**Comment by araujobsd** [comment]
Sounds great! Yes, sometimes developers get distracted with other things and forget to backporting things from FreeBSD HEAD to other FreeBSD versions, I can talk for myself about that. :)

Thanks again!

**Comment by araujobsd** [comment]
Thank you too! I felt strange the rest of that code nmdm and bhyveload appears in this pull request, because actually those codes were not part of this PR. I got very confused with that.

If times permit, I will try to send a PR for bhyve virtio-scsi.

Thanks again.

**Comment by araujobsd** [comment]
Oopps, there is the nmdm and bhyveload you want to check! Feel free to close the PR if you want.

Best,

**Pull request closed without merging**
