### PR TITLE
Add centos8.conf 

### PR DESCRIPTION
**Pull request by TheHades**

### CODE REVIEW

**Review by michael-o — APPROVED** [review]

**Comment by michael-o** [comment]
I think this is basically useless these days and should be renamed to `almalinux8.conf`. CentOS 8 is dead.

**Review by michael-o — CHANGES_REQUESTED** [review]
Just used this to install AlmaLinux 8. Works for me. @TheHades Can you please change title, commit message and filename?

**Comment by TheHades** [comment]
@michael-o I think it would make more sense to create a new pull request.

**Comment by michael-o** [comment]
> @michael-o I think it would make more sense to create a new pull request.

I am fine with that.

**Pull request closed without merging**
