### PR TITLE
Create centos7.conf

### PR DESCRIPTION
**Pull request by carriercomm**
Latest kernel for CentOS 7 - additionally, I have resolved the disk issue. It automatically boots now as it should after installation.

Using CentOS latest
Tested against: net install

### CODE REVIEW

**Comment by churchers** [comment]
Hi @carriercomm 

Thanks for providing a template for CentOS 7

Small point but you shouldn't need the `linux_kernel` option any more as it's specified directly in the `grub_run` options. We don't use that setting anywhere now. We don't really use the `guest` setting either now, although it still appears in `vm list|info` output for 1.0 users.

Also, does your CentOS7 boot partition have a `/grub2/grub.cfg` file? On my system I was able to get 7 to boot just by specifying the following option in the config (instead of the `grub_runX` options).

    grub_run_dir="/grub2"

This picked up the guests own grub configuration file and displayed the standard CentOS boot menu with normal/rescue boot options. Using the guests own grub config is preferred if it exists as it will hopefully be kept up to date by the guest if any changes/updates are made.

**Comment by carriercomm** [comment]
Thanks,
 No grub2 folder and it required it on my system. Kept saying please enter boot kernel on the grub line. As for the rest - I hadn't realized. I was originally running a pkg install until I synced your git folder. The pkg install is 0.9xx. This is on FreeBSD 11.

Thanks!
Kevin

**Comment by carriercomm** [comment]
Maybe there is a difference in the bhyve-grub (or grub2-bhyve can't remember the name right this second) installer between bsd 10-11 or a difference in the pkg install. I did not install bhyve until after I found your tool. Once I found it - I decided to use bhyve. However, never installed it until after your tools instructions to install grub. (This is due to bhyve being included in FreeBSD 11)

Maybe - provide an installation procedure or just a checkup for requirements in your instructions. Not sure what the best option is - I know my situation is odd... 

Anyway, I can try removing those lines and give it a shot later today when I'm at work. After I synced your git I was finally on 1.0-p1 I think or something like that. I'll be happy to test. Just wanted to make note that your installer worked perfectly from git. I honestly was avoiding bhyve until I found your tool. Now I'm so pleased I'm finally able to maybe convert my VM's and switch the servers to FreeBSD. (I say maybe based on performance.)

Thank you again for the hard work.

**Comment by churchers** [comment]
Ahh I wish I could get rid of that 0.9 version in pkg, the Linux support in that version was horrible and the `grub_install|grub_run` options were not supported. Unfortunately FreeBSD defaults to the quarterly package database, which contains port builds that can be months old :(. The ports tree and pkg-latest have 1.0-p2, which is vastly improved. (1.0+ also has a foreground mode which is really useful for installs `# vm -f install guest iso`).

When you synced with GitHub did you choose the 1.0-stable branch? If you sync with master you should get 1.1. (The only real difference at the moment being "datastores" in 1.1)

**Comment by m3lloa** [comment]
Guys,

Trying to create a CentOS 7 VM but no luck so far.

The latest minimal is CentOS-7-x86_64-Minimal-1611.iso.

Installing on vmware, I see gruub with:

```
setparams 'CentOS Linux (3.10.0-514.el7.x86_64) 7 (Core)'

	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_msdos
	insmod xfs
	set root='hd0,msdos1'
```

So changed centos7.conf to reflect 3.10.0-514.el7.x86_64.

The installation finished without any issues and was performed with all default setting for partition - lvm.

The vm won't start and display:

```
error: file `/vmlinuz-3.10.0-514.el7.x86_64' not found.
error: you need to load the kernel first.

Press any key to continue...
```
After installation I see the following partitions:


```
grub> ls
(lvm/cl-root) (lvm/cl-home) (lvm/cl-swap) (hd0) (hd0,msdos2) (hd0,msdos1) (host
)
```
Below the conf file:

```
loader="grub"
cpu=1
memory=512M
network0_type="virtio-net"
network0_switch="public"
disk0_type="virtio-blk"
disk0_name="disk0.img"
grub_install0="linux /isolinux/vmlinuz LANG=en_US.UTF-8 KEYTABLE=us SYSFONT=latarcyrheb-sun16 consol
grub_install1="initrd /isolinux/initrd.img"
grub_run0="linux /vmlinuz-3.10.0-514.el7.x86_64 root=/dev/mapper/centos-root LANG=en_US.UTF-8 KEYTAB
grub_run1="initrd /initramfs-3.10.0-514.el7.x86_64.img"
uuid="dbcb0c6c-7b97-11e7-a225-001517983c2a"
network0_mac="58:9c:fc:0d:0c:c9"

```

Any help will be appreciated.

**Pull request merged**
