### PR TITLE
Remove grub_run_dir from Debian template.

### PR DESCRIPTION
**Pull request by olgeni**
Debian seems to hang at grub prompt if grub_run_dir is set, otherwise it works just fine.

### CODE REVIEW

**Comment by EpiJunkie** [comment]
For LVM installations I believe this directive is required. Maybe adding a comment to reference that would be more prudent?

**Comment by olgeni** [comment]
Good point - let me check this.

**Comment by easye** [comment]
Confirmed as the right change from my recent (Nov. 2016) experience.  Without this change, instances created from the debian template stop in the bootloader.

To boot from such hung instances, one may enter
```
grub> configfile /boot/grub/grub.cfg
```

**Comment by churchers** [comment]
Thanks

**Pull request merged**
