### PR TITLE
Added a how to for custom sparse zvol.

### PR DESCRIPTION
**Pull request by oodgaard**

### CODE REVIEW

**Comment by oodgaard** [comment]
Add a bit more info to this if you think it's a bit sparse. It helped me out though :)

**Comment by churchers** [comment]
Thanks for the commit. When you're the main dev and know everything inside out it's hard to know whether the documentation makes sense or is missing things.

I will pull this into the readme although I will probably add a few things.
First off, if the zvol is directly under the guest you should just be able to add the following to the config:

```
disk1_type="virtio-blk"
disk1_name="disk1"
disk1_dev="sparse-zvol"
```
If the device type is `zvol` or `sparse-zvol`, the path `/dev/zvol/{VM_DATASET}/{GUEST}/{DISK_NAME}` gets used automatically.

Also there is a command which can help add disks to an existing guest

```
vm add -d disk -t sparse-zvol -s 50G guest
```

It's worth browsing through the man page. There's a lot more in that than the readme.

**Comment by oodgaard** [comment]
This was primarily how to add a zvol to a different zpool and use it with vm. I have a vm on an ssd and want to have gigabytes of sample data to test with on another disk.

**Comment by churchers** [comment]
Ah ok, the device path gave me the impression it was in the same place as the original guest. Yeah to use a disk image anywhere else requires using the custom option.

**Pull request merged**
