### PR TITLE
added support for bhyve_flags in vm file config

### PR DESCRIPTION
**Pull request by ehasting**
Suggestion to #162

### CODE REVIEW

**Comment by ehasting** [comment]
example config:
loader="bhyveload"
cpu=2
memory=2G
uefi="false"
network0_type="virtio-net"
network0_switch="public"
disk0_type="virtio-blk"
disk0_name="disk0"
disk0_dev="sparse-zvol"
uuid="<magic-uuid>"
network0_mac="<oh-my-mac>"
bhyve_flags="-w"

**Comment by theory14** [comment]
I need this flag, too.  My CPU is an AMD A10-7860K.   I've manually patched my copy, but would like to have this option in the package.

I think the bigger issue is somewhere in bhyve since the -w is supposed to be for debug purposes.  Incidentally, I have OpenBSD VM running fine without the need for this patch.

**Comment by cactus** [comment]
I would love to have this feature too. 👍

**Comment by churchers** [comment]
This feature has been implemented. (Note there's also a specific `ignore_bad_msr` config option as well)

**Pull request closed without merging**
